version: "3"

services:
  pasteme-frontend:
    image: registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-frontend:3.2.2
    container_name: pasteme-frontend
    depends_on:
      - pasteme-backend
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 45s
      timeout: 3s
      retries: 3
    restart: always
    ports:
      - 8020:8080
    volumes:
      - ./frontend/logs/:/var/lib/pasteme/
      - ./frontend/usr/:/www/pasteme/usr/

  pasteme-backend:
    image: registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-go-backend:3.2.1
    container_name: pasteme-backend
    depends_on:
      - pasteme-mysql
    healthcheck:
      test: ["CMD", "wget", "localhost:8000/?method=beat", "--output=/dev/null"]
      interval: 45s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - ./backend/config/:/config/
      - ./backend/data/:/data/

  pasteme-mysql:
    image: mysql:5.5
    container_name: pasteme-mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 45s
      timeout: 3s
      retries: 3
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pasteme
      MYSQL_MAX_ALLOWED_PACKET: 128M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
    volumes:
      - ./mysql:/var/lib/mysql
