version: '3'
services:
    mongo:
        image: mongo
        volumes:
            - ./mongo/db:/data/db   # /data/db是container中存放数据位置
        ports:
            - 27017:27017
        restart: always

        
    mongo-express:
        links:
            - mongo  # 这里关联到mongo的container
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: 123456

    mysql:
        image: mysql
        ports:
            - 33060:33060
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: 123456  
            
    adminer:
        links:
            - mysql
        image: adminer
        restart: always
        ports:
            - 8080:8080
        

    redis:
        image: redis
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
        volumes:
            - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/db/:/data/