version: "3"
services:
  mongodb:
    image: "mongo:4.1"
    container_name: "mongo"
    restart: "always"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=passwd"
      - "MONGO_INITDB_DATABASE=yapi"
    volumes:
      - "mongodb-db:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodb-db: